blank_issues_enabled: false
contact_links:
  - name: Pytania ogólne / dyskusje
    url: https://discord.com/channels/865183769626279966/906826197508435968
    about: Użyj Dyskusji do luźnych pytań i pomysłów, które nie są błędem ani FR.
